---
name: GHDL Testbench
on: [push]
jobs:
  Student-Testbench:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHDL nightly
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm
      - run: ghdl --version
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ghdl analyze -v src/hdl/thirtyOneDayMonth.vhd
      - run: ghdl analyze -v src/hdl/thirtyOneDayMonth_tb.vhd
      - run: ls -R
      - run: ghdl elaborate -v thirtyOneDayMonth_tb
      - run: ghdl run -v thirtyOneDayMonth_tb

  Instructor-Testbench:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GHDL nightly
        uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm
      - run: ghdl --version
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cat .github/testfile | base64 -d > src/hdl/thirtyOneDayMonth_tb.vhd
      - run: ghdl analyze -v src/hdl/thirtyOneDayMonth.vhd
      - run: ghdl analyze -v src/hdl/thirtyOneDayMonth_tb.vhd
      - run: ls -R
      - run: ghdl elaborate -v thirtyOneDayMonth_tb
      - run: ghdl run -v thirtyOneDayMonth_tb
